import Head from 'next/head';
import { Fragment } from 'react';
import ArtistCard from '../components/ArtistCard';
import styles from './Home.module.css';

const artistList = [
  {
    id: 'jordan-rakei',
    name: 'Jordan Rakei',
    genre: 'R&B/Soul',
    src: '/images/jordan-rakei-profile.jpg',
    alt: 'Jordan Rakei Profile Picture',
  },
  {
    id: 'tom-misch',
    name: 'Tom Misch',
    genre: 'Pop',
    src: '/images/tom-misch-profile.jpg',
    alt: 'Tom Misch Profile Picture',
  },
  {
    id: 'yussef-dayes',
    name: 'Yussef Dayes',
    genre: 'Jazz',
    src: '/images/yussef-dayes-profile.jpg',
    alt: 'Yussef Dayes Profile Picture',
  },
  {
    id: 'lawerence',
    name: 'Lawerence',
    genre: 'Pop',
    src: '/images/lawerence-profile.jpg',
    alt: 'Clyde and Gracie Lawerence',
  },
  {
    id: 'hiatus-kaiyote',
    name: 'Hiatus Kaiyote',
    genre: 'R&B/Soul',
    src: '/images/hiatus-kaiyote-profile.jpg',
    alt: 'Hiatus Kaiyote Profile Picture',
  },
  {
    id: 'snarky-puppy',
    name: 'Snarky Puppy',
    genre: 'Rock/Jazz/Funk',
    src: '/images/snarky-puppy-profile.jpg',
    alt: 'Snarky Puppy Profile Picture',
  },
];

export default function Home() {
  return (
    <Fragment>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <section className={styles.heroSection}>
          <h1>Better Music</h1>
        </section>

        <section className={styles.artistSection}>
          <h2>Artists</h2>

          <ul className={styles.artistCardsContainer}>
            {artistList.map((artist, index) => {
              return (
                <li key={`artist-${index}`}>
                  <ArtistCard
                    name={artist.name}
                    id={artist.id}
                    genre={artist.genre}
                    src={artist.src}
                    alt={artist.alt}
                  />
                </li>
              );
            })}
          </ul>
        </section>
      </main>
    </Fragment>
  );
}
